### ISSUE TITLE
how to use ?

### ISSUE THREAD

**Issue by jeanphilippegoldman** [GateNLP/gateplugin-Lang_French#2]
Hi,
I have a naive question. In the CREOLE plugin manager of Gate, I loaded the Lang_French plugin.
Msg window says : CREOLE plugin loaded: Language: French
But it does not appear as a processing ressource.
Now, how to use it ? 
thanks for your answer

**Comment by greenwoodma** [comment]
Once you've loaded the plugin, if you right click on applications, and then ready made applications you should find a new entry for the French application.

Can I suggest you direct similar questions to the [mailing list](https://gate.ac.uk/mail/) in the future as you are more likely to get quick responses. Bugs etc. should still be reported here though.
